# Generated by Django 6.0.2 on 2026-02-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_clinica', '0002_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='valor_consulta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
