# Generated by Django 6.0.2 on 2026-02-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_clinica', '0003_consulta_valor_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico/Sintomas'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='prescricao',
            field=models.TextField(blank=True, null=True, verbose_name='Prescrição Médica'),
        ),
    ]
