# Generated by Django 6.0.2 on 2026-02-11 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_clinica', '0004_consulta_diagnostico_consulta_prescricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['-data', '-horario'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['nome'], 'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['nome'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='horario',
            field=models.TimeField(verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_clinica.medico', verbose_name='Médico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_clinica.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='valor_consulta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=20, unique=True, verbose_name='CRM'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(max_length=50, verbose_name='Especialidade'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
